dappx/urls.py
from django.conf.urls import url
from . import views
# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^candidate_register/$',views.candidate_register, name='candidate_register'),
    url(r'^ballot_box/$',views.ballot_box, name='ballot_box'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

dappx/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime 
# Create your models here.
class VoterProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
   
    mother = models.CharField(max_length=128)
    father = models.CharField(max_length=128)
    birth_city = models.CharField(max_length=128)
    birth_district = models.CharField(max_length=128)
    gender = models.CharField(max_length=128)


class CandidateProfileInfo(models.Model):
    #id = models.CharField(primary_key=True, max_length=128)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    party = models.CharField(max_length=128, blank=True)
    independent_status = models.BooleanField(default=False)
    constituency = models.CharField(max_length=128, blank = True)


def __str__(self):
  return self.user.username


class CandidateVote(models.Model):
    #candidateProfile  = models.OneToOneField(CandidateProfileInfo, on_delete=models.CASCADE)
    candidate_vote_id = models.AutoField(primary_key = True)
    candidate_id = models.CharField(max_length=128)

dappx/forms.py
from django import forms
from dappx.models import VoterProfileInfo, CandidateProfileInfo, CandidateVote
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
class UserForm(forms.ModelForm):
    username = forms.CharField(label='CNIC', validators=[RegexValidator('(\d{5}-\d{7}-\d{1})', message="CNIC should be in the format xxxxx-xxxxxxx-x")], widget=forms.TextInput(attrs={'class':'form-control','placeholder':'CNIC'}))
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}))
    last_name = forms.CharField(label='Last Name', widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}))  
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    email = forms.EmailField(label  ='Email', widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'xxx@yyy.zzz'}))
    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'password', 'email')

class VoterProfileInfoForm(forms.ModelForm):
    
    CHOICES = (('male', 'Male',), ('female', 'Female',))

    #id = forms.CharField(label="CNIC", validators=[RegexValidator('(\d{13})', message="CNIC should be in the format xxxxx-xxxxxxx-x")], widget=forms.TextInput(attrs={'class':'form-control','placeholder':"CNIC Number"}))
    mother = forms.CharField(label="Mother's name", widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Mother's Name"}))
    father = forms.CharField(label="Father's name", widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Father's Name"}))
    gender = forms.ChoiceField(label='Gender', widget=forms.RadioSelect, choices=CHOICES)
    birth_city = forms.CharField(label="Birth City", widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Birth City"}))
    birth_district = forms.CharField(label="Birth District", widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Birth District"}))
    
    class Meta():
        model = VoterProfileInfo
        fields = ( 'mother' , 'father', 'gender', 'birth_city', 'birth_district')

class CandidateProfileInfoForm(forms.ModelForm):

    CHOICES = (('PPP', 'PPP',), ('MQM', 'Mutahida Qoumi Movement',), ('PTI', 'Pakistan Tehreek-e-Insaf'))

    #id = forms.CharField(label="CNIC", widget=forms.TextInput(attrs={'class':'form-control','placeholder':"CNIC Number"}))
    #independent_status = forms.BooleanField(label='Independent Status', required=False)
    #party = forms.ChoiceField(label='Political Party', widget=forms.RadioSelect, choices=CHOICES, required=False)


    class Meta():
        model = CandidateProfileInfo
        fields = ()

class BallotBox(forms.ModelForm):

    class Meta():
        model = CandidateVote
        fields = ()

dappx/views.py
from django.shortcuts import render
from dappx.forms import UserForm,VoterProfileInfoForm, CandidateProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from dappx.models import CandidateProfileInfo, CandidateVote
from dappx.helper import server, districtGenerator, queryCandidateInfo
import requests
import json
from django.core import serializers



def index(request):
    return render(request,'dappx/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = VoterProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():            
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            fullName = str(user.first_name)+str(user.last_name)
            voter_profile = {
                    "$class" : "org.ecp.voting.voter", 
                    "voterID":  user.username,
                    "fullName" : str(fullName),
                    "gender" : str(profile.gender)
            }
            ifVoted_data = {
                 "$class": "org.ecp.voting.ifVoted",
                 "voterID": user.username,
                 "votedOrNot": "false"
            }

            requests.post(server+'/api/voter', json = voter_profile)
            requests.post(server+'/api/ifVoted', json = ifVoted_data)

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = VoterProfileInfoForm()
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def candidate_register(request):
    registered = False
    constituency_list = []
    i=0
    contituency = requests.get(server+'/api/district').json()
    while(i < len(contituency)):
        constituency_list.append(( contituency[i]["districtName"] ))
        i= i+1
    political_parties = requests.get(server+'/api/politicalParty').json()
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = CandidateProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.constituency = request.POST['const']
            profile.party = request.POST['party'] 
            profile.save()
            fullName = str(user.first_name)+str(user.last_name)
            district_url = server+'/api/queries/filterDistrictByName?nameParam={}'.format(request.POST['const'])
            url = server+'/api/queries/PartyByNames?partyParam={}'.format(request.POST['party'])
            district_info = requests.get(district_url).json()
            political_party_data = requests.get(url).json()
            candidate_vote_id_data = CandidateVote.objects.create(candidate_id= str(user.username))
            candidateVoteId = str(candidate_vote_id_data.candidate_vote_id)
            candidate_data = {
                "$class": "org.ecp.voting.candidate",
                "candidateID": str(user.username),
                "fullName": fullName,
                "party": political_party_data[0],
                "IndependentStatus": "false"
            }
            candidate_vote_data = {
                "$class": "org.ecp.voting.candidateVote",
                "candidateVoteId": candidateVoteId,
                "totalVote": "0",
                "candidateProfile": candidate_data,
                "candidateDistrict": district_info[0]
            }           
            candidate_payload = json.dumps(candidate_data)
            candidate_data_request = requests.post(server+'/api/candidate', json = candidate_data)
            requests.post(server+'/api/candidateVote', json = candidate_vote_data)
            registered = True


        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = CandidateProfileInfoForm()
    return render(request,'dappx/candidate_registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered,
                           'constituencies':constituency_list,
                           'parties': political_parties})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})


def ballot_box(request):
    voted = False

    political_parties = requests.get(server+'/api/politicalParty')
    resp = political_parties.json()
    if request.user.is_authenticated:
        contituency = districtGenerator(request.user.username)
        contituency_name = str(contituency['districtName'])
        constituency_candidates = CandidateProfileInfo.objects.filter(constituency=contituency_name)
        if request.method == 'POST':
            voted=True
            selected_cadidate_id = str(request.POST['candidate'])
            candidatesVote_resp = requests.get(server+'/api/candidateVote').json()
            selected_candidate_id = queryCandidateInfo(candidatesVote_resp, len(candidatesVote_resp), selected_cadidate_id)
            candidate_vote_asset = "resource:org.ecp.voting.candidateVote#{}".format(selected_candidate_id)
            ifVotedAsset = "resource:org.ecp.voting.ifVoted#{}".format(request.user.username)
            vote={
                    "$class": "org.ecp.voting.vote",
                    "candidateVoteAsset": candidate_vote_asset,
                    "ifVotedAsset": ifVotedAsset
            }
            print(vote)

            print(requests.post(server + '/api/vote', json=vote))

    return render(request,'dappx/ballot.html' , { 'candidates' : constituency_candidates })

templates/dappx/ballot.html
{% extends "dappx/base.html" %}
{% load my_filters %}
{% load staticfiles %}
{% block body_block %}
<style>
    .radiotext {
        margin: 10px 10px 0px 0px;
    }

    .center-align{
        text-align: center
    }
</style>
  <div class="container">
    <div class="jumbotron"> 
        <form  method="post">
            {% csrf_token %}
            <div class="row">
                    <div class="col-lg-6" >
                        <div class="panel panel-default" >
                            <div class="panel-heading center-align">
                                Ballot Box
                            </div>
                            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover">
                                        <thead>                                           
                                            <tr>
                                                <th class="center-align">First Name</th>
                                                <th class="center-align">Party</th>
                                            </tr>                                            
                                        </thead>
                                        <tbody>
                                            <div class="form-group">
                                                {% for value in candidates %}                                         
                                                <tr>
                                                    <td >
                                                        <div class="radio">
                                                            <label for="choice{{ forloop.counter }}"><input type="radio" name="candidate" id="candidate{{ forloop.counter }}" value="{{ value.user.username }}">{{ value.user.first_name }}</label>
                                                        </div>
                                                    </td>
                                                    <td class="center-align"> {{ value.party }}</td>
                                                </tr>                                       
                                                {% endfor %}
                                            </div>
                                        </tbody>
                                    </table>
                                </div>
                                <input type="submit" value="Vote" class="btn btn-primary" style="float: right;">
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
        </form>

    </div>
  </div>

 
{% endblock %}

templates/dappx/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">   
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'dappx/vendor/bootstrap/css/bootstrap.min.css' %}" >

    <!-- MetisMenu CSS -->
    <link href="{% static 'dappx/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'dappx/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'dappx/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    
    {#bootstrap admin panel#}
    <div id="wrapper">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'index' %}">Voting System</a>
                    </div>
                    <!-- /.navbar-header -->
        
                    <ul class="nav navbar-top-links navbar-right">
                        <!-- /.dropdown -->
                        
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                            </a>           
                            <ul class="dropdown-menu dropdown-user">      
                                {% if user.is_authenticated %}
                                <li><a href="#"><i class="fa fa-user fa-fw"></i> {{ user.first_name }}</a>
                                </li>
                                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                                </li>
                                {% else %}                             
                                <li><a href="{% url 'dappx:user_login' %}"><i class="fa fa-sign-in fa-fw"></i> Login</a>
                                </li>
                                {% endif %}
                            </ul>         
                            <!-- /.dropdown-user -->
                        </li>
                        
                        <!-- /.dropdown -->
                    </ul>
                    <!-- /.navbar-top-links -->
        
                    <div class="navbar-default sidebar" role="navigation">
                        <div class="sidebar-nav navbar-collapse">
                            <ul class="nav" id="side-menu">

                                <li>
                                    {% if user.is_authenticated %}
                                    <a href="#"><i class="fa fa-user fa-fw"></i> Profile</a>
                                    <li>
                                            <a href="{% url 'dappx:ballot_box' %}"><i class="fa fa-dashboard fa-fw"></i> Ballot Box</a>
                                    </li>
                                    {% else %}
                                    <a href="#"><i class="fa fa-sign-in fa-fw"></i> Registration<span class="fa arrow"></span></a>
                                    <ul class="nav nav-second-level">
                                        <li>
                                            <a href="{% url 'dappx:candidate_register' %}">Candidate</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'dappx:register' %}">Voter</a>
                                        </li>
                                    </ul>
                                    {% endif %}
                                    
                                    <!-- /.nav-second-level -->
                                </li>                               
                            </ul>
                        </div>
                        <!-- /.sidebar-collapse -->
                    </div>
                    <!-- /.navbar-static-side -->
                </nav>
    </div>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

    <script src="{% static 'dappx/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dappx/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'dappx/vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'dappx/vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'dappx/vendor/morrisjs/morris.min.js' %}"></script>
    <script src="{% static 'dappx/data/morris-data.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dappx/dist/js/sb-admin-2.js' %}"></script>
  </body>
</html>

templates/dappx/candidate_registration.html
{% extends "dappx/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="font-weight: bold">
                            Candidate Registration Form
                        </div>
                        <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <form enctype="multipart/form-data" method="POST">
                                                {% csrf_token %}
                                                {{ user_form.as_p }}
                                                {{ profile_form.as_p }}
                                                <div class="form-group">
                                                    <label>Constituency</label>
                                                    <select class="form-control", name= "const">
                                                        {% for constituency in constituencies %}
                                                        <option>{{ constituency }}</option>
                                                        {% endfor %}
                                                    </select>
                                                </div>
                                                <div class="form-group">
                                                        <label>Party</label>
                                                        {% for party in parties %}
                                                        <div class="radio">
                                                                <label for="choice{{ forloop.counter }}"><input type="radio" name="party" id="party{{ forloop.counter }}" value="{{ party.politicalPartyName }}">{{ party.politicalPartyName }}</label>
                                                        </div>
                                                        {% endfor %}
                                                </div>                                                                 
                                                <input type="submit" class="btn btn-primary" name="" value="Register">
                                                <button type="reset" class="btn btn-primary">Reset Button</button>
                                        </form>
                                    </div>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        
      {% endif %}
    </div>
  </div>

 
{% endblock %}

<script>function Hide()
        {
            if(document.getElementById('mainselect').options[document.getElementById('mainselect').selectedIndex].value == "1")
            {
                 document.getElementById('a').style.display = 'none';
                 document.getElementById('b').style.display = '';
            }else
            {
                 document.getElementById('a').style.display = '';
                 document.getElementById('b').style.display = 'none'
            }
        }
        </script>

templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Voting System !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.first_name }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="CNIC">CNIC:</label>
          <input type="text" name="username" placeholder="CNIC">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/dappx/registration.html
{% extends "dappx/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="font-weight: bold">
                            Voter Registration Form
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form enctype="multipart/form-data" method="POST">
                                            {% csrf_token %}
                                            {{ user_form.as_p }}
                                            {{ profile_form.as_p }}                              
                                            <input type="submit" class="btn btn-primary" name="" value="Register">
                                            <button type="reset" class="btn btn-primary">Reset Button</button>
                                    </form>
                                </div>
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        
      {% endif %}
    </div>
  </div>

 
{% endblock %}